name: Deploy to Sevalla

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        cd backend && npm install
        cd ../frontend && npm install
    
    - name: Lint code
      run: |
        echo "Linting would run here"
        # npm run lint
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    
    - name: Test build
      run: |
        echo "Build tests would run here"
        # npm test

  deploy-sevalla:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Sevalla
      run: |
        echo "Sevalla deployment triggered by GitHub push"
        echo "Sevalla will automatically deploy from this repository"
        echo "Check your Sevalla dashboard for deployment status"